backend:
  name: git-gateway
  branch: main
collections:
  - name: activities
    label: Activities
    label_singular: Activity
    folder: 'src/pages/activities'
    create: true
    slug: '{{slug}}'
    summary: '{{date | date("MMMM DD, YYYY")}}: {{title}}'
    view_groups:
      - label: Cause
        field: cause
    fields:
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'layouts/ActivityLayout.astro',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'MMMM DD, YYYY',
          time_format: false,
          picker_utc: true,
        }
      - {
          label: 'Cause',
          name: 'cause',
          widget: 'select',
          options:
            [
              'Diabetes',
              'Vision',
              'Hunger',
              'Environment',
              'Childhood Cancer',
              'Other',
            ],
        }
      - { label: 'Location', name: 'location', widget: 'string' }
      - {
          label: 'Number of people served',
          name: 'served',
          widget: 'number',
          value_type: int,
        }
      - { label: 'Short description', name: 'description', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          allow_multiple: false,
        }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          buttons:
            [
              'bold',
              'italic',
              'link',
              'heading-three',
              'heading-four',
              'quote',
              'bulleted-list',
              'numbered-list',
            ],
          editor_components: ['image'],
        }
media_folder: 'uploads'
public_folder: '/uploads'
site_url: https://www.lcbprerana.org/
