backend:
  name: git-gateway
  branch: main
media_folder: 'uploads'
public_folder: '/uploads'
site_url: https://www.lcbprerana.org/
collections:
  - name: activities
    label: Activities
    label_singular: Activity
    create: true
    folder: 'src/pages/activities'
    preview_path: 'activities/{{slug}}'
    slug: '{{slug}}'
    summary: "{{title}} - {{date | date('MMMM DD, YYYY')}} by {{commit_author}}"
    sortable_fields: ['date', 'commit_date', 'title']
    view_groups:
      - label: Cause and Project Type
        field: causeAndProjectType
    fields:
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'layouts/ActivityLayout.astro',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          allow_multiple: false,
        }
      - { label: 'Short description', name: 'description', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD',
          date_format: 'MMMM DD, YYYY',
          time_format: false,
          picker_utc: false,
        }
      - {
          label: 'Cause and Project Type',
          name: 'causeAndProjectType',
          widget: 'select',
          options:
            [
              'Childhood Cancer: Childhood Cancer Awareness, Education and Advocacy',
              'Childhood Cancer: Organization or Facility Assistance',
              'Childhood Cancer: Entertainment and Recreational',
              'Childhood Cancer: Child and Family Tutoring',
              'Childhood Cancer: Family Assistance',
              'Childhood Cancer: Professional Training and Support',
              'Childhood Cancer: Other Childhood Cancer Service Activity',
              'Diabetes: Diabetes Retreats, Camps and Symposiums',
              'Diabetes: Strides for Diabetes Awareness and Prevention',
              'Diabetes: Diabetes Support Group',
              'Diabetes: Healthy Living for Type 2 Diabetes',
              'Diabetes: Healthy Eating for Gestational Diabetes',
              'Diabetes: Recreational Facility Improvement Event',
              'Diabetes: Type 2 Diabetes Risk Awareness and Screening',
              'Diabetes: Diabetes Education and Advocacy',
              'Diabetes: Other Diabetes Service Activity',
              'Environment: Tree Planting and Tree Care',
              'Environment: Clean Water and Sanitation',
              'Environment: Environmental Awareness, Education and Advocacy',
              'Environment: Environmental Clean Up and Restoration',
              'Environment: Recycling and Waste Management',
              'Environment: Other Environment Service Activity',
              'Hunger: Food Collection and Food Banks',
              'Hunger: Meal Preparation and Distribution',
              'Hunger: Community Gardens and Agriculture',
              'Hunger: Hunger Awareness, Education and Advocacy',
              'Hunger: Other Hunger Service Activity',
              'Vision: Vision Screening',
              'Vision: Support Services for the Blind or Visually Impaired',
              'Vision: Eyeglass Collection and Recycling',
              'Vision: Lions Eye Banks',
              'Vision: Vision Awareness, Education and Advocacy',
              'Vision: Other Vision Service Activity',
              'Other: Awareness, Education and Advocacy',
              'Other: Assistance to an Individual',
              'Other: Disaster Preparedness and Relief',
              'Other: Education, Literacy or Reading Action Program',
              'Other: Lions Quest',
              'Other: Other Health Service Project',
              'Other: Other Service Activity',
            ],
        }
      - { label: 'Location', name: 'location', widget: 'string' }
      - {
          label: 'Number of people served',
          name: 'served',
          widget: 'number',
          value_type: int,
        }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          buttons:
            [
              'bold',
              'italic',
              'link',
              'heading-three',
              'heading-four',
              'quote',
              'bulleted-list',
              'numbered-list',
            ],
          editor_components: ['image'],
        }
  - label: Pages
    name: pages
    files:
      - label: 'About Page'
        name: about
        file: 'src/data/about.json'
        preview_path: 'about'
        fields:
          - { label: Image, name: image, widget: image }
          - {
              label: About the club,
              name: about,
              widget: markdown,
              buttons:
                [
                  'bold',
                  'italic',
                  'link',
                  'heading-three',
                  'heading-four',
                  'quote',
                  'bulleted-list',
                  'numbered-list',
                ],
              editor_components: ['image'],
            }
          - label: Officers
            name: officers
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Photo, name: photo, widget: image }
